### ISSUE TITLE
关于飞牛影视 能不能用 这个302

### ISSUE THREAD

**Issue by caidada406688233** [AmbitiousJun/go-emby2openlist#149]
我现在 openlist  挂载 123 网盘
然后用webdav 挂载到飞牛本地

配置文件如下 

```yaml
emby: 
  host: http://192.168.1.57:8005                     飞牛影视端口
  mount-path: /vol02/1000-1-8331b469       飞牛影视挂载dav路径
  episodes-unplay-prior: true             
  resort-random-items: true                 
  # 代理异常处理策略
  # origin: 代理回源服务器处理
  # reject: 拒绝处理
  proxy-error-strategy: origin
  # 图片质量, 默认请求原图
  # 配置范围: [1, 100]
  # 建议范围: [70, 90]
  # 具体数值根据自己的实际情况作调整
  images-quality: 100
  strm:                                      # 远程视频 strm 配置
    # 路径映射, 将 strm 文件内的路径片段替换成指定路径片段

  # emby 下载接口处理策略
  #    403: 禁用下载接口, 返回 403 响应
  # origin: 代理到源服务器
  # direct: 获取并重定向到直链地址
  download-strategy: 403
  # emby 本地媒体根目录
  # 检测到该路径为前缀的媒体时, 代理回源处理
  local-media-root: /data/local

# 该配置仅针对通过磁盘挂载方式接入的网盘, 如果你使用的是 strm, 可忽略该配置
openlist:
  host: http://192.168.1.57:5244            # openlist 访问地址
  token: alist-****

```

代理不成功，求助
